--- 
apiVersion: v1 
kind: Pod 
metadata: 
  name: airflow-worker 
  namespace: airflow 
spec: 
  containers: 
    - name: base 
      imagePullPolicy: IfNotPresent 
      image: 'apache/airflow:latest' 
      env: 
      - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN 
        value: "postgresql://admin:admin@postgres:5432/postgresdb" 
      - name: AIRFLOW__CORE__EXECUTOR 
        value: "LocalExecutor" 
      - name: AIRFLOW__KUBERNETES__NAMESPACE 
        value: "airflow" 
      - name: AIRFLOW__CORE__DAGS_FOLDER 
        value: "/opt/airflow/dags" 
      - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS 
        value: "True" 
      - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE 
        value: "True"          
      volumeMounts: 
        - name: logs-pv 
          mountPath: /opt/airflow/logs 
        - name: dags-pv 
          mountPath: /opt/airflow/dags 
  restartPolicy: Never 
  securityContext: 
    runAsUser: 50000 
    fsGroup: 50000 
  serviceAccountName: "airflow-scheduler" 
  volumes: 
    - name: dags-pv 
      persistentVolumeClaim: 
        claimName: dags-pvc 
    - name: logs-pv 
      persistentVolumeClaim: 
        claimName: logs-pvc